{% set name = "bleak-winrt" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bleak-winrt-{{ version }}.tar.gz
  sha256: 0577d070251b9354fc6c45ffac57e39341ebb08ead014b1bdbd43e211d2ce1d6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - python
    - pip
    - scikit-build
  run:
    - python

test:
  imports:
    - bleak_winrt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dlech/bleak-winrt
  summary: Python WinRT bindings for Bleak
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
